### ISSUE TITLE
How does documentation is generated by Dingo?

### ISSUE THREAD

**Issue by igorsantos07** [nilportugues/laravel5-jsonapi-dingo#8]
I was wondering how documentation is generated using Dingo's commands, as it relies on PHPDoc annotations, and by design `laravel5-json-api` doesn't require you to write almost any code... Are there guides or examples on how does that part of integration work?

**Comment by nilportugues** [comment]
You can still provide the PHP Docs on the objects you're serializing... but this package does not rely on them and does not provide them. 

But you can certainly add them on the Transformer classes and it should work.
